apiVersion: v1
kind: ServiceAccount
metadata:
  name: appdynamics-infraviz
---
apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: appd-windows-infra-agent
spec: 
  selector:
    matchLabels:
      name: appd-windows-infra-agent
  template: 
    metadata: 
      labels: 
        name: appd-windows-infra-agent
    spec:
      nodeSelector:
        #beta.kubernetes.io/os: windows
        kubernetes.io/os: windows
        kubernetes.io/arch: amd64
        #cloud.google.com/gke-nodepool: windows-pool
      #tolerations:
      # - key: "node.kubernetes.io/os"
      #   operator: "Equal"
      #   value: "windows"
      #   effect: "NoSchedule"
      serviceAccountName: appdynamics-infraviz
      volumes:
      - name: windows-ma-log-config
        configMap:
          name: windows-ma-log-config
      containers:
      - name: appd-windows-infra-agent
        image:  iogbole/machine-agent-windows-64bit:20.6.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: windows-ma-config
        env:
        - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: appd-key
              name: appd-secret
        resources:
          limits:
            cpu: "0.6"
            memory: "2Gi"
          requests:
            cpu: "0.3"
            memory: "1G"
        ports:
          - containerPort: 9090
       # Windows doesn't allow file mount at this time, only directories can be mounted. 
       # volumeMounts:
       # - name: windows-ma-log-config
       #   mountPath: \appdynamics\machineagent\conf\logging\log4j.xml
       #   subPath: log4j.xml  
      restartPolicy: Always   
---
apiVersion: v1
kind: Service
metadata:
  name: appd-windows-infra-agent-service
spec:
  selector:
    name: appd-windows-infra-agent
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090 
status:
  loadBalancer: {}
